# Generated by Django 6.0.4 on 2026-05-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
